# Generated by Django 4.2.10 on 2026-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_v1_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiehrstoragemodel',
            name='contact_email',
            field=models.EmailField(blank=True, default='hello@wiehr.cc', help_text='GET FULL PACK -> EMAIL. Where someone writes to buy the full version; you issue them a License by hand afterwards.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='wiehrstoragemodel',
            name='contact_telegram',
            field=models.URLField(blank=True, default='https://t.me/Wiehr', help_text='GET FULL PACK -> TELEGRAM. Same purpose as Contact Email.', verbose_name='Contact Telegram'),
        ),
        migrations.AddField(
            model_name='wiehrstoragemodel',
            name='preview_file',
            field=models.FileField(blank=True, help_text='A free sample anyone can download without a key — e.g. Wiehr_Drum_Kit_V1.0-PREVIEW.zip. Served straight from the item page; leave empty and the DOWNLOAD PREVIEW button does not render.', null=True, upload_to='storage/previews/', verbose_name='Preview File'),
        ),
        migrations.AlterField(
            model_name='wiehrstoragemodel',
            name='purchase_url',
            field=models.URLField(blank=True, default='', help_text='Not rendered anywhere. Kept for a future storefront — the item page now sends people to Contact Email / Contact Telegram instead of to a shop.', max_length=500, verbose_name='Purchase URL'),
        ),
    ]
