# Generated by Django 4.2.10 on 2026-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_storage_preview_and_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiehrstoragemodel',
            name='license_covers',
            field=models.TextField(blank=True, default='', help_text='Section 1 of the license agreement — what this product actually consists of, in the licensee\'s copy. Plain text, one item per line, "•" for bullets. A font lists its styles and codepages; a drum kit lists its instruments and formats. Leave empty and the agreement falls back to a generic description built from Title and File Type.', verbose_name='License Covers'),
        ),
    ]
