# Generated by Django 4.2.10 on 2026-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_storage_license_covers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiehrstoragemodel',
            name='download_label',
            field=models.CharField(blank=True, default='', help_text='What the unlocked download button says. Leave empty for "DOWNLOAD FULL PACK". A font is not a pack — set it to "DOWNLOAD FONT", "DOWNLOAD PROJECT", whatever the thing is.', max_length=40, verbose_name='Download Button Label'),
        ),
    ]
